"""tweaked validation code for available_copies in book

Revision ID: 00f57bb11ac7
Revises: 79145d3d11e1
Create Date: 2026-02-06 20:56:24.170369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00f57bb11ac7'
down_revision: Union[str, Sequence[str], None] = '79145d3d11e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('loan', 'status',
               existing_type=postgresql.ENUM('borrowed', 'returned', 'overdue', name='loanstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loan', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('borrowed', 'returned', 'overdue', name='loanstatus'),
               existing_nullable=False)
    op.alter_column('book', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
