"""tweaked validation code for available_copies in book

Revision ID: 641f8180d6cf
Revises: e9e106a683b7
Create Date: 2026-02-05 13:09:33.459947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '641f8180d6cf'
down_revision: Union[str, Sequence[str], None] = 'e9e106a683b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
