"""tweaked validation code for available_copies in book

Revision ID: 79145d3d11e1
Revises: 8ea1352c626d
Create Date: 2026-02-06 19:47:12.138143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79145d3d11e1'
down_revision: Union[str, Sequence[str], None] = '8ea1352c626d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
