"""empty message

Revision ID: 80a48f710dc2
Revises: 9441b9fe071d
Create Date: 2026-02-04 13:30:00.724622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

loanstatus = postgresql.ENUM('borrowed', 'returned', 'overdue', name='loanstatus')

# revision identifiers, used by Alembic.
revision: str = '80a48f710dc2'
down_revision: Union[str, Sequence[str], None] = '9441b9fe071d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    loanstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('loan', sa.Column('status', loanstatus, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'status')
    loanstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
