"""tweaked validation code for available_copies in book

Revision ID: 8ea1352c626d
Revises: 1a8f7e40051d
Create Date: 2026-02-06 18:36:59.716384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ea1352c626d'
down_revision: Union[str, Sequence[str], None] = '1a8f7e40051d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
