"""tweaked validation code for available_copies in book

Revision ID: 902aa314c715
Revises: 641f8180d6cf
Create Date: 2026-02-05 14:02:54.276033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '902aa314c715'
down_revision: Union[str, Sequence[str], None] = '641f8180d6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'available_copies',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
